name: Test Dispatch and Call

on:
  workflow_dispatch:
    inputs:
      workflow_dispatch_call:
        description: "Send to workflow_dispatch_call.yml in kb-oss-parent?"
        type: boolean
        required: true
        default: true

jobs:
  test-various-workflow:
    name: "Testing Only"
    runs-on: ubuntu-22.04
    steps:
      - name: "Testing send to dispatch_and_call.yml in kb-oss-parent"
        env:
          GH_WORKFLOW_PAT: ${{ secrets.GH_WORKFLOW_PAT }}
          OWNER: xsalefter
          REPO: kb-oss-parent
        # using double quote in request body because we need to parse variable from string
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_WORKFLOW_PAT}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
            -d "{\"event_type\":\"repository_workflow_together\", \"client_payload\": {\"hello-msg\": \"Hello From Testing\", \"is-exist\": \"true\"}}"

      - name: "Testing send to workflow_dispatch_call.yml in kb-oss-parent"
        if: github.event.inputs.workflow_dispatch_call == 'true'
        env:
          GH_WORKFLOW_PAT: ${{ secrets.GH_WORKFLOW_PAT }}
          OWNER: xsalefter
          REPO: kb-oss-parent
        run: |
          PROJECT_VERSION="0.0.0-SNAPSHOT"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_WORKFLOW_PAT}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/actions/workflows/workflow_dispatch_call.yml/dispatches \
            -d "{\"ref\": \"master\", \"inputs\": {\"hello-msg\": \"Hello From Testing workflow_dispatch_call.yml $PROJECT_VERSION\", \"is-exist\": \"true\" }}"
